### ISSUE TITLE
Can you teach Eileen to run scrape-util on command?

### ISSUE THREAD

**Issue by eileenpeppard** [erdl/legacy-scrape-util#17]
Hey, guys,

We are changing current transducers down at the Frog buildings this Friday afternoon and i want to be able to look at the data soon after and not have to wait for the cron job to run. Can you teach me how to run it?

Thanks.
Eileen

**Comment by eileenpeppard** [comment]
In my notes, I have these written down to use at the command line:
--to run the portion that processes DHHL hobo files:
`scrape-util -p dhhl-hobo-u12`
--to run the portion that processes the Maui hobo files:
`scrape-util -p hobo-u12`

**Comment by carlosparadis** [comment]
Hi Eileen, 

As far as I am aware, there is no way to run just the webctrl portion. What you can do is run scrape-util project wise. The name of the commands you are exemplifying match the name of the folders:

`dhhl  dhhl-hobo-u12  hobo-u12  marine-center-egauge  maui-egauge  occupant-query  uhm-frog`

So my best guess would be for you to type:

`scrape-util -p frog_uhm`

On Putty. 

Forrest added scrape-util script runnable from any folder in the server, so you really just need to type the above if you want to re-run everything manually from frog_uhm.

I would, of course, recommend you to test it since everything involving scrape-utils is guessing.

**Comment by eileenpeppard** [comment]
Okay I’ll test it.

**Comment by eileenpeppard** [comment]
I ran `scrape-util -p uhm-frog` and something happened but got errors at end and did not see new data uploaded to table. Here are screenshots.
![scrape-util -p uhm-frog runs but error at end 1](https://user-images.githubusercontent.com/29083044/32808507-5372ac6c-c937-11e7-9cd8-d64e19c94df3.PNG)
![scrape-util -p uhm-frog runs but error at end 2](https://user-images.githubusercontent.com/29083044/32808513-56a7fce8-c937-11e7-82e8-18d72f903d38.PNG)

**Comment by carlosparadis** [comment]
In the 2nd to last line int he screenshot you sent me says "Permission denied". This means you need sudo:

`sudo scrape-util -p uhm-frog`

Type this and then your server password afterwards and press enter.

**Comment by eileenpeppard** [comment]
And it's nearly 45 minutes late in doing the scrape-util on the cron job. I hope i did not mess it up totally.... Okay I'll try your suggestion, Carlos.

**Comment by eileenpeppard** [comment]
Okay, it WORKED!!! yeay!!

**Comment by carlosparadis** [comment]
Great! I am closing the issue and moving this to the scrape-util wiki wiki if we ever need it again :-)
